# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('num_of_min_days', models.IntegerField()),
                ('num_of_max_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Itenary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('head_description', models.TextField()),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('best_seasons_to_visit', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('autumn', 'Autumn'), ('spring', 'Spring')], max_length=10)),
                ('associated_adventures', models.ManyToManyField(blank=True, null=True, to='homepage.Adventure')),
                ('destination', models.ManyToManyField(blank=True, null=True, to='homepage.Destination')),
                ('itenary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Itenary')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('head_description', models.TextField()),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('associated_adventures', models.ManyToManyField(blank=True, null=True, to='homepage.Adventure')),
                ('destination', models.ManyToManyField(blank=True, null=True, to='homepage.Destination')),
                ('itenary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Itenary')),
            ],
        ),
    ]
