# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20180328_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingtrip',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upcomingtrip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
