# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_upcomingtrip_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationpackage',
            name='logo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
