# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-06 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_destinationpackage_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinationpackage',
            old_name='price',
            new_name='price_for_one',
        ),
        migrations.AddField(
            model_name='destinationpackage',
            name='price_for_eighteen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationpackage',
            name='price_for_four',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationpackage',
            name='price_for_seven',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationpackage',
            name='price_for_twelve',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
