# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-06 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20180406_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinationimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='destinationpackage',
            old_name='associated_adventures',
            new_name='included_adventure',
        ),
        migrations.AddField(
            model_name='destination',
            name='about_destination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='associated_adventures',
            field=models.ManyToManyField(blank=True, to='homepage.Adventure'),
        ),
        migrations.AddField(
            model_name='destinationpackage',
            name='destination_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Destination'),
        ),
    ]
