# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-06 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20180406_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
