# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-06 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_destinationimage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationimage',
            name='title',
        ),
    ]
