# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-06 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_remove_destinationimage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationpackage',
            name='destination',
        ),
        migrations.AddField(
            model_name='destinationpackage',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Destination'),
        ),
    ]
