# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-06 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20180406_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinationimage',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationimages', to='homepage.Destination'),
        ),
    ]
