# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-09 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_auto_20180409_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure_package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price_per_person', models.IntegerField()),
                ('logo', models.CharField(max_length=200)),
                ('adventure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.Adventure')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Destination')),
            ],
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationimages', to='homepage.Destinationpackage'),
        ),
    ]
