# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-09 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_auto_20180409_1114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adventure_package',
            new_name='Adventurepackage',
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationimages', to='homepage.Destinationpackage'),
        ),
    ]
