# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-09 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_auto_20180409_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventurepackage',
            name='adventure',
        ),
        migrations.AddField(
            model_name='adventurepackage',
            name='adventure',
            field=models.ManyToManyField(to='homepage.Adventure'),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationimages', to='homepage.Destinationpackage'),
        ),
    ]
