# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-09 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_auto_20180409_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('tent', 'Tent'), ('sleepingbag', 'Sleepingbag'), ('rucksack', 'RuckSack'), ('accessory', 'Accessory')], max_length=20)),
                ('price_per_day', models.IntegerField()),
                ('price_after_three_days', models.IntegerField()),
                ('logo', models.CharField(max_length=200)),
                ('associated_adventure', models.ManyToManyField(to='homepage.Adventure')),
            ],
        ),
        migrations.AddField(
            model_name='adventurepackage',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationimages', to='homepage.Destinationpackage'),
        ),
    ]
