# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-09 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_auto_20180409_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='associated_adventure_package',
            field=models.ManyToManyField(null=True, related_name='adventure_linked', to='homepage.Adventurepackage'),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationimages', to='homepage.Destinationpackage'),
        ),
    ]
