# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-10 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_auto_20180410_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingtrip',
            name='departure',
            field=models.CharField(default='Delhi', max_length=50),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationimages', to='homepage.Destinationpackage'),
        ),
    ]
