# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-16 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0031_auto_20180416_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('icon', fontawesome.fields.IconField(blank=True, max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='addon',
            name='destination_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='homepage.Destinationpackage'),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationimages', to='homepage.Destinationpackage'),
        ),
        migrations.AddField(
            model_name='destinationpackage',
            name='inclusions',
            field=models.ManyToManyField(blank=True, null=True, to='homepage.Inclusion'),
        ),
        migrations.AddField(
            model_name='upcomingtrip',
            name='inclusions',
            field=models.ManyToManyField(blank=True, null=True, to='homepage.Inclusion'),
        ),
    ]
