# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-25 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0033_auto_20180416_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationpackage',
            name='property_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationpackage',
            name='property_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='destination_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='homepage.Destinationpackage'),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationimages', to='homepage.Destinationpackage'),
        ),
        migrations.AlterField(
            model_name='destinationpackage',
            name='inclusions',
            field=models.ManyToManyField(related_name='inclusions_packages', to='homepage.Inclusion'),
        ),
    ]
