# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-28 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0039_auto_20180509_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThingsToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('logo', models.FileField(upload_to='documents/ThingsToDo')),
                ('destination', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Destination')),
            ],
        ),
        migrations.AlterField(
            model_name='addon',
            name='destination_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='homepage.Destinationpackage'),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationimages', to='homepage.Destinationpackage'),
        ),
    ]
