# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-09 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0043_auto_20180823_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventuredestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('associated_adventures', models.ManyToManyField(blank=True, to='homepage.Adventure')),
                ('vendor_destination', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='Adventuregear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adventureimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Adventurevendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('contact_number', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('associated_adventure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Adventure')),
                ('destination', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Adventuredestination')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_of_year', models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='adventurepackage',
            old_name='sno',
            new_name='level_of_difficulty_on_5',
        ),
        migrations.RemoveField(
            model_name='adventurepackage',
            name='adventure',
        ),
        migrations.RemoveField(
            model_name='adventurepackage',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='adventurepackage',
            name='logo',
        ),
        migrations.AddField(
            model_name='adventurepackage',
            name='adventure_form',
            field=models.CharField(choices=[('landbased', 'Landbased'), ('waterbased', 'Waterbased'), ('airbased', 'Airbased')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='adventurepackage',
            name='group_prices',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adventurepackage',
            name='notes_for_activity',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adventurepackage',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='destination_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='homepage.Destinationpackage'),
        ),
        migrations.AlterField(
            model_name='adventurepackage',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Destination'),
        ),
        migrations.AlterField(
            model_name='adventurepackage',
            name='price_per_person',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adventurepackage',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationimages', to='homepage.Destinationpackage'),
        ),
        migrations.AddField(
            model_name='adventureimage',
            name='adventure_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventureimages', to='homepage.Adventurepackage'),
        ),
        migrations.AddField(
            model_name='adventurepackage',
            name='months_of_year',
            field=models.ManyToManyField(blank=True, to='homepage.Month'),
        ),
        migrations.AddField(
            model_name='adventurepackage',
            name='required_gear',
            field=models.ManyToManyField(blank=True, to='homepage.Adventuregear'),
        ),
        migrations.AddField(
            model_name='adventurepackage',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Adventurevendor'),
        ),
    ]
