# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-22 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0065_auto_20181111_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Howdystays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('property_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('price_per_room', models.IntegerField(blank=True, null=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='StayAddon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('destination_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Howdystaysaddons', to='homepage.Howdystays')),
            ],
        ),
        migrations.CreateModel(
            name='Stayimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Howdystaysimages', to='homepage.Howdystays')),
            ],
        ),
        migrations.AlterField(
            model_name='addon',
            name='destination_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='homepage.Destinationpackage'),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationimages', to='homepage.Destinationpackage'),
        ),
    ]
